config/routes.rb
BookshopApp::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "devise/passwords",
                                    registrations: "devise/registrations", confirmations: "devise/confirmations" }
  root 'static_pages#home'

  resources :products do
    collection do
      get 'search'
    end
  end

  resource :cart do
    member do
      post 'add_to'
      post 'remove_from'
      get 'remove_all_cart_items'
      post 'update_cart_items'
    end
  end
  
  namespace :admin do
    resources :products
  end

  resources :categories

end

app/views/shared/_cart.html.haml
.col-right.sidebar
  .block.block-cart#cart-content
    .block-title
      %strong
        %span My Cart

    .block-content
      - if @current_cart.nil? || @current_cart.cart_items.count.zero?
        %p.empty You have no items in your shopping cart
      - else
        .summary
          %p.amount
            There are
            = link_to pluralize(@current_cart.cart_items.count, "item"), cart_path(@current_cart)
            in your cart
          %p.subtotal
            %span.label Cart Subtotal:
            %span.price
              = format_price(@current_cart.total)

        %p.block-subtitle Recently added item(s)

        %ol#cart-sidebar.mini-products-list

          %li.item
            = render partial: 'shared/cart_item', collection: @current_cart.cart_items

app/views/shared/_cart_item.html.haml
- unless cart_item.id.nil?
  %li.item
    = link_to product_path(cart_item.product), title: cart_item.title, class: "product-image" do
      = image_tag image_for(cart_item.product), size: "50x50", alt: cart_item.title
    .product-details
      = link_to remove_from_cart_path(cart_item_id: cart_item.id), method: :post do
        %img{ title: "Remove This Item", class:  "btn-remove"}
      %p.product-name
        = link_to cart_item.title, product_path(cart_item.product)
      %strong= cart_item.quantity
      x
      %span.price= format_price(cart_item.price)

app/views/shared/_messages.html.haml
#messages_product_view
  %ul.messages
    - if flash[:success] || flash[:notice]
      %li.success-msg
        %ul
          %li
            %span= flash[:success] || flash[:notice]
    - if flash[:alert]
      %li.error-msg
        %ul
          %li
            %span= flash[:alert]

app/views/shared/_product.html.haml
%li.item
  .product-image
    = link_to product_path(product) do
      = image_tag image_for(product), size: "135x135", alt: product.title
  %h2.product-name
    = link_to product.title, product_path(product)
  .price-box
    %span#product-price-168.regular-price
      %span.price= format_price(product.price)
  - unless product.stock.zero?
    .actions
      = form_tag add_to_cart_path do
        = hidden_field_tag "product_id", product.id
        = hidden_field_tag "quantity", 1
        = button_tag "Add to cart", class: "button btn-cart" do
          %span
            %span Add to Cart