config/routes.rb
BookshopApp::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "devise/passwords",
                                    registrations: "devise/registrations", confirmations: "devise/confirmations" }
  root 'static_pages#home'

  resources :products do
    collection do
      get 'search'
    end
  end

  resource :cart do
    member do
      post 'add_to'
      post 'remove_from'
      get 'remove_all_cart_items'
      post 'update_cart_items'
    end
  end
  
  namespace :admin do
    resources :products
  end

  resources :categories

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  belongs_to :user

  def update(user)
    user_cart = user.cart
    if user_cart
      update_cart_items(user_cart)
    else
      update_attribute(:user_id, user.id)
    end
  end

  def add(product, qty)
    qty = qty.to_i.abs
    if existing_cart_item?(product)
      existing_cart_item =  cart_items.find_by(product_id: product.id)
      new_quantity = existing_cart_item.quantity + qty
      existing_cart_item.update_attribute(:quantity, new_quantity)
    else
      cart_item = cart_items.build(product: product, quantity: qty, title: product.title, price: product.price)
      cart_item.save
    end

    update_total
  end

  def remove(cart_item)
    cart_items.find_by(id: cart_item.id).destroy

    update_total
  end

  def remove_all_cart_items
    cart_items.destroy_all

    update_total
  end

  def update_quantity_cart_items(options)
    cart_items.where(id: options.keys).each do |cart_item|
      value = options[cart_item.id.to_s].to_i.abs
      cart_item.update_attribute(:quantity, value)
    end

    update_total
  end

  def update_total
    total = cart_items.inject(0.00) {|total, cart_item| total + cart_item.price * cart_item.quantity}

    update_attribute(:total, total)
  end

  def validate_quantity
    cart_items.each do |cart_item|
      cart_item.update_if_not_in_stock
    end
    update_total
  end

  def remove_items_from_stock
    cart_items.each do |cart_item|
      cart_item.update_product_stock
    end
  end

  private

  def existing_cart_item?(product)
    cart_items.find_by(product_id: product.id)
  end

  def update_cart_items(user_cart)
    # Merges the current_cart and the user's cart.

    cart_items.each do |cart_item|
      existing_cart_item = user_cart.cart_items.find_by(product_id: cart_item.product_id)

      if existing_cart_item
        existing_cart_item.increment!(:quantity, cart_item.quantity)
      else
        cart_item.update_attribute(:cart_id, user_cart.id)
      end
    end

    user_cart.update_total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user, only: :show

  def add_to
    @product = Product.find_by(id: params[:product_id])
    @current_cart.add(@product, params[:quantity].to_i)
    flash[:success] = "#{ @product.title } was added to your shopping cart"

    redirect_to request.env["HTTP_REFERER"]
  end

  def remove_from
    @cart_item = CartItem.find_by(id: params[:cart_item_id])
    @current_cart.remove @cart_item

    redirect_to request.env["HTTP_REFERER"]
  end

  def remove_all_cart_items
    @current_cart.remove_all_cart_items

    redirect_to cart_path(@current_cart)
  end

  def show
    @cart = @current_cart
  end

  def update_cart_items
    @current_cart.update_quantity_cart_items(params[:cart_item])

    redirect_to cart_path(@current_cart)
  end
end

app/views/carts/_cart_item.html.haml
%tr.first{class: cycle("odd", "even")}
  %td
    = link_to product_path(cart_item.product) do
      = image_tag image_for(cart_item.product), size: "75x75", class: "product-img"
  %td
    %h2.product-name
      = link_to cart_item.product.title, product_path(cart_item.product)
  %td.a-right
    %span.cart-price
      %span.price= format_price(cart_item.product.price)
  %td.a-center
    = text_field_tag "cart_item[#{ cart_item.id }]", cart_item.quantity, class: "input-text qty", maxlength: "12", size: "4", title: "Qty"
  %td.a-right
    %span.cart-price
      %span.price= format_price(cart_item.quantity * cart_item.product.price)
  %td.a-center.last
    = link_to "Remove item", remove_from_cart_path(cart_item_id: cart_item.id), method: :post, class: "btn-remove btn-remove2"

app/views/carts/_existing_cart_items.html.haml
.page-title.title-buttons
  %h1 Shopping Cart
= form_tag update_cart_items_cart_path, method: "post" do
  %fieldset
    %table#shopping-cart-table.data-table.cart-table
      %colgroup
        %col{width: "1"}/
        %col/
        %col{width: "1"}/
        %col{width: "1"}/
        %col{width: "1"}/
        %col{width: "1"}/
        %col{width: "1"}/
      %thead
        %tr.first.last
          %th{rowspan: "1"}
          %th{rowspan: "1"}
            %span.nobr Product Name
          %th.a-center{colspan: "1"}
            %span.nobr Unit Price
          %th.a-center{rowspan: "1"} Qty
          %th.a-center{colspan: "1"} Subtotal
          %th.a-center{rowspan: "1"}
      %tfoot
        %tr.first.last
          %td.a-right.last{colspan: "50"}
            = link_to root_url, method: :get, class: "button btn-continue" do
              %span
                %span Continue Shopping
            = button_tag class: "button btn-update", type: "submit" do
              %span
                %span Update Shopping Cart
            = link_to remove_all_cart_items_cart_path, method: "get", id: "empty_cart_button", class: "button btn-empty", name: "update_cart_action" do
              %span
                %span Clear Shopping Cart
      %tbody
        = render partial: 'cart_item', collection: @cart.cart_items
.cart-collaterals
  .totals
    %table#shopping-cart-totals-table
      %colgroup
        %col/
        %col{width: "1"}/
      %tfoot
        %tr
          %td.a-right{colspan: "1", style: ""}
            %strong Grand Total
          %td.a-right{style: ""}
            %strong
              %span.price= format_price(@cart.total)

app/views/carts/_non_existing_cart_items.html.haml
.page-title.title-buttons
  %h1 Shopping Cart
%h3 You have no items in your cart

app/views/carts/add_to.js.erb
$("#cart-content").html("<%= escape_javascript(render partial: 'shared/cart' ) %>");

app/views/carts/show.html.haml
.main-container.col1-layout
  .main
    .col-main
      .cart
        - if @cart.cart_items.exists?
          = render 'existing_cart_items'
        - else
          = render 'non_existing_cart_items'

app/views/carts/update.js.erb
$("#cart-content").html("<%= escape_javascript(render partial: 'shared/cart' ) %>");