config/routes.rb
BookshopApp::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "devise/passwords",
                                    registrations: "devise/registrations", confirmations: "devise/confirmations" }
  root 'static_pages#home'

  resources :products do
    collection do
      get 'search'
    end
  end

  resource :cart do
    member do
      post 'add_to'
      post 'remove_from'
      get 'remove_all_cart_items'
      post 'update_cart_items'
    end
  end
  
  namespace :admin do
    resources :products
  end

  resources :categories

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_one :image, validate: true

  validates :title, presence: true, length: { minimum: 3 }
  validates :price, presence: true, numericality: { greater_than: 0.0 }
  validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :category_id, presence: true

  scope :available, ->(available) { where((available == 'soon') ? 'stock = 0' : 'stock > 0') }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticated_admin

  def index
    products_filter_order = ProductsFilterOrder.new(ParamsSanitizer.new(filter_params).sanitize_all)
    @products = products_filter_order.paginate

    @categories = Category.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.build_image(filename: params[:product][:image])

    if @product.save
      flash[:success] = "Products added successfully."
      redirect_to admin_products_path
    else
      flash.now[:error] = "Please try again."
      render 'new'
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.image.destroy
    @product.destroy
    flash[:success] = "Product removed successfully."

    redirect_to admin_products_path
  end

  private

  def filter_params
    params.permit(:search, :page, :stock, :category)
  end

  def product_params
    params.require(:product).permit(:title, :category_id, :short_description,
                                    :price, :description, :stock)
  end

  # Before action

  def authenticated_admin
    redirect_to root_path if !current_user || !current_user.is_admin?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
  end

  def search
    products_filter_order = ProductsFilterOrder.new(ParamsSanitizer.new(search_params).sanitize_all)
    @all_products = products_filter_order.search
    @products = products_filter_order.apply_all_and_paginate

    render 'categories/show'
  end

  private

  def search_params
    params.permit(:page, :direction, :sort, :category)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def product_availability(stock)
    stock.zero? ? "Out of stock" : stock
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def format_price(number)
    #Formats a number with 2 decimals
    "£" + number_with_precision(number, :precision => 2)
  end

  def availability(stock)
    stock.zero? ? "Out of stock" : "In stock"
  end

  def image_for(product)
    Rails.application.assets.find_asset(product.image[:filename]).nil? ? "default_book_cover.jpg" : product.image[:filename]
  end

end

app/views/admin/products/_product.html.haml
%tr{ class: cycle("", "alternate-row") }
  %td= product.title
  %td= product.category.label
  %td= format_price(product.price)
  %td= product_availability(product.stock)
  %td.options-width
    = link_to "", admin_product_path(product), method: :delete, class: "icon-2 info-tooltip"

app/views/admin/products/index.html.haml
#page-heading
  %h1 Product list
- if flash[:success]
  =  render 'admin/shared/success_message'
%table#content-table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %th.sized{:rowspan => "3"}
      = image_tag "side_shadowleft.jpg", size: "20x300"
    %th.topleft
    %td#tbl-border-top
    %th.topright
    %th.sized{:rowspan => "3"}
      = image_tag "side_shadowright.jpg", size: "20x300"
  %tr
    %td#tbl-border-left
    %td
      #content-table-inner
        #table-content
          %form#mainform{:action => ""}
            %table#product-table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
              %tr
                %th.table-header-repeat.line-left.minwidth-1
                  = link_to "Product name", "#"
                %th.table-header-repeat.line-left.minwidth-1
                  = link_to "Category", "#"
                %th.table-header-repeat.line-left.minwidth-1
                  = link_to "Price", "#"
                %th.table-header-repeat.line-left
                  = link_to "Stock", "#"
                %th.table-header-repeat.line-left
                  = link_to "Options", "#"
              = render partial: "product", collection: @products
        %table#paging-table{:border => "0", :cellpadding => "0", :cellspacing => "0"}
          %tr
            %td
              = link_to "", admin_products_path(params.merge(page: 1)), class: "page-far-left"
              = link_to "", admin_products_path(params.merge(page: prev_page(@products))), class: "page-left"
              #page-info
                Page
                %strong= @products.current_page
                of
                = @products.total_pages
              = link_to "", admin_products_path(params.merge(page: next_page(@products))), class: "page-right"
              = link_to "", admin_products_path(params.merge(page: @products.total_pages)), class: "page-far-right"
        .clear
    %td#tbl-border-right
  %tr
    %th.sized.bottomleft
    %td#tbl-border-bottom
    %th.sized.bottomright

app/views/admin/products/new.html.haml
#page-heading
  %h1 Add product
- if flash[:error]
  =  render 'admin/shared/error_message'
%table#content-table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %th.sized{:rowspan => "3"}
      = image_tag "side_shadowleft.jpg", size: "20x300"
    %th.topleft
    %td#tbl-border-top
    %th.topright
    %th.sized{:rowspan => "3"}
      = image_tag "side_shadowright.jpg", size: "20x300"
  %tr
    %td#tbl-border-left
    %td
      #content-table-inner
        = form_for @product, url: admin_products_path(@product), method: "post", :html => { :multipart => true } do |f|
          %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
            %tr{:valign => "top"}
              %td
                %table#id-form{:border => "0", :cellpadding => "0", :cellspacing => "0"}
                  %tr
                    %th{:valign => "top"} Product name:
                    %td
                      = f.text_field :title, class: "inp-form", required: true
                    - if @product.errors[:title][0]
                      %td
                        .error-left
                        .error-inner= @product.errors[:title][0].capitalize
                  %tr
                    %th{:valign => "top"} Category:
                    %td
                      = f.select :category_id, options_for_select(@categories.each.map {|category| [category.label, category.id] }, selected: params[:category], id: "category_id", class: "select")
                    %td
                  %tr
                    %th{:valign => "top"} Price:
                    %td
                      = f.number_field :price, class: "inp-form", required: true
                      - if @product.errors[:price][0]
                        %td
                          .error-left
                          .error-inner= @product.errors[:price][0].capitalize
                  %tr
                    %th Image:
                    %td
                      = f.file_field :image
                    - if @product.image && @product.image.errors[:filename][0]
                      %td
                        .error-left
                        .error-inner= @product.image.errors[:filename][0].capitalize
                  %tr
                    %th{:valign => "top"} Stock:
                    %td
                      = f.number_field :stock, class: "inp-form", required: true
                    - if @product.errors[:stock][0]
                      %td
                        .error-left
                        .error-inner= @product.errors[:stock][0].capitalize
                  %tr
                    %th
                    %td{:valign => "top"}
                      = f.button "Submit", class: "form-submit"
                      = f.button "Reset", class: "form-reset", type: "submit"
                    %td
        .clear
    %td#tbl-border-right
  %tr
    %th.sized.bottomleft
    %td#tbl-border-bottom
    %th.sized.bottomright
.clear