config/routes.rb
BookshopApp::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "devise/passwords",
                                    registrations: "devise/registrations", confirmations: "devise/confirmations" }
  root 'static_pages#home'

  resources :products do
    collection do
      get 'search'
    end
  end

  resource :cart do
    member do
      post 'add_to'
      post 'remove_from'
      get 'remove_all_cart_items'
      post 'update_cart_items'
    end
  end
  
  namespace :admin do
    resources :products
  end

  resources :categories

end

app/views/layouts/_admin_navigation.html.haml
.table
  %ul.current
    %li
      = link_to "#" do
        %b Products
      .select_sub.show
        %ul.sub
          %li
            = link_to "Add Product", new_admin_product_path
          %li
            = link_to "List Products", admin_products_path
  .nav-divider
  .clear
.clear

app/views/layouts/_header.html.haml
.header-container
  .header
    .quick-access
      %p.welcome-msg= welcome_message
      %ul.links
        %li.first
          = link_to "My Cart", cart_path(@current_cart), title: "My Cart", class: "top-link-cart"
        - if user_signed_in?
          %li.last
            = link_to "Logout", destroy_user_session_path, method: "delete"
        - else
          %li.last
            = link_to "Sign in", new_user_session_path

app/views/layouts/_navigation.html.haml
.nav-container
  #nav
    - @categories.each do |category|
      %li.level0.nav-1.level-top.first
        = link_to category_path(category), class: "level-top" do
          %span
            = category.label

app/views/layouts/admin.html.haml
!!!
%html
  %head
    !!!
    %title Admin
    = stylesheet_link_tag "admin/screen.css", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #page-top-outer
      #page-top
        .clear
    .clear
    .nav-outer-repeat
      .nav-outer
        #nav-right
          .showhide-account
            = link_to destroy_user_session_path, method: "delete" do
              = image_tag "nav_logout.gif", size: "64x14"
          .clear
        .nav
          = render 'layouts/admin_navigation'
      .clear
    .clear
    #content-outer
      #content
        = yield
      .clear
    .clear
    #footer
      .clear

app/views/layouts/application.html.haml
!!!
%html
%head
  %title BookshopApp
  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
%body
.wrapper
  .page
    = render 'layouts/header'
    = render 'layouts/navigation'
    = yield